baseURL = 'https://howtoxiny.org/'
title = 'How to X in Y'

enableGitInfo = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
disableKinds = ["section"]

[params]
repo = "https://github.com/nobe4/howtoxiny"


[languages]
[languages.en]
    languageName = "English"
    contentDir = "content/en"
[languages.fr]
    languageName = "Fran√ßais"
    contentDir = "content/fr"
[languages.de]
    languageName = "Deutsch"
    contentDir = "content/de"

[taxonomies]
y = "y"
x = "x"

# Cascade is configured from ./config/_default/hugo.toml
# Use ./script/cascade to generate.
# Can't use cascade.yaml yet https://github.com/gohugoio/hugo/issues/12899

[markup]
[markup.highlight]
noClasses = false # using this to disable the syntax highlighting

[build]
noJSConfigInAssets = true
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = 'tailwind\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
